name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push the Docker image
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker build . --file Dockerfile --tag ghcr.io/dsmaugy/skeleton-listener/bot:latest
        docker push ghcr.io/dsmaugy/skeleton-listener/bot:latest
