name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to container registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build Docker image
      run: | 
        docker build . --file Dockerfile --tag ghcr.io/dsmaugy/skeleton-listener/bot:latest \
         --build-arg DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
         --build-arg YOUTUBE_API=${{ secrets.YOUTUBE_API }}
    - name: Push Docker image
      run: docker push ghcr.io/dsmaugy/skeleton-listener/bot:latest
